# Generated by Django 4.2.20 on 2025-10-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
