"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!)fc^8@3a=9bym(=ot876x3x^mt(0%spwdu+o%k2#_g_@asq_n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api.apps.ApiConfig',  # Use custom AppConfig for AI service initialization
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS and CSRF for front-end dev server(s)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list([
    'accept', 'accept-encoding', 'authorization', 'content-type', 'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with', 'x-client-id'
])
CORS_EXPOSE_HEADERS = ['X-Client-Id']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
]

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Basic REST framework defaults (minimal for now)
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Console logging for requests and our app
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# AI Configuration
AI_MODEL_PROVIDER = os.getenv('AI_MODEL_PROVIDER', 'ollama')
AI_MODEL_NAME = os.getenv('AI_MODEL_NAME', 'mistral:7b-instruct')
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')
AI_MAX_TOKENS = int(os.getenv('AI_MAX_TOKENS', '200'))
AI_TEMPERATURE = float(os.getenv('AI_TEMPERATURE', '0.7'))
AI_API_KEY = os.getenv('AI_API_KEY', '')  # For OpenAI, Gemini, Claude

# Production settings (Render)
import logging
logger = logging.getLogger(__name__)

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Read configuration from environment variables (production environment)
if os.getenv('RENDER') or os.getenv('DATABASE_URL'):
    # Production environment configuration
    DEBUG = os.getenv('DEBUG', 'False') == 'True'
    SECRET_KEY = os.getenv('SECRET_KEY', SECRET_KEY)
    
    # Allowed hosts (Render will automatically provide domain)
    # Get from environment or use default
    allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '')
    if allowed_hosts_str:
        ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]
    else:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    
    # Add Render domain (if exists)
    render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
    if render_host:
        ALLOWED_HOSTS.append(render_host)
    
    # For production, also add common Render patterns
    # Note: Django doesn't support wildcards, so we need to add specific domains
    # The RENDER_EXTERNAL_HOSTNAME should handle this automatically
    
    # Database configuration - Use SQLite by default for reliability
    # PostgreSQL can be configured via DATABASE_URL if needed
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
    # Optionally try PostgreSQL if DATABASE_URL is set and valid
    DATABASE_URL = os.getenv('DATABASE_URL')
    if DATABASE_URL and dj_database_url:
        try:
            db_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
            # Only use PostgreSQL if hostname contains render.com (external) or is localhost
            host = db_config.get('HOST', '')
            if host and ('render.com' in host or 'localhost' in host or '127.0.0.1' in host):
                DATABASES = {
                    'default': db_config
                }
                try:
                    logger.info(f'Using PostgreSQL database: {host}')
                except:
                    pass
            else:
                # Internal Render hostname (dpg-xxx-a) may not resolve immediately
                # Use SQLite instead for reliability
                try:
                    logger.info(f'PostgreSQL hostname {host} may not be accessible. Using SQLite.')
                except:
                    pass
        except Exception as e:
            try:
                logger.warning(f'PostgreSQL configuration failed: {e}. Using SQLite.')
            except:
                pass
    
    # Static files configuration
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Add WhiteNoise middleware (after SecurityMiddleware)
    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    
    # CORS configuration (read frontend domain from environment variable)
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
    # Add frontend URL to CORS and CSRF
    if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
    if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
    
    # Allow all origins in production (temporary fix for CORS)
    CORS_ALLOW_ALL_ORIGINS = True
